spring:
    application:
        name: Flex API
    h2:
        console:
            enabled: true
    jpa:
        show-sql: false

liquibase:
    contexts: dev

github:
   username: lovelyliatroim
   token: dce4b8ad10dad49a0b1b3f9da6b64cfbfaf401e3
