spring:
    datasource:
      db_admin_pool:
        type: com.zaxxer.hikari.HikariDataSource
        url: jdbc:postgresql://postgres-db:5432/postgres
        username: flex_admin
        password: flex_admin_prod_#432
      application_pool:
        type: com.zaxxer.hikari.HikariDataSource
        url: jdbc:postgresql://postgres-db:5432/postgres
        username: flex_app
        password: flex_app_prod_#981
    jpa:
      show-sql: false
      properties:
        hibernate:
          default_schema: flex_admin

logging:
  file: /var/log/flex/flex-api.log
