spring:
    application:
        name: Flex API
    h2:
        console:
            enabled: false
    datasource:
      db_admin_pool:
        type: com.zaxxer.hikari.HikariDataSource
        url: jdbc:h2:file:./target/h2db/db/flexApiDb;DB_CLOSE_DELAY=-1
        username: gm
        password:
      application_pool:
        type: com.zaxxer.hikari.HikariDataSource
        url: jdbc:h2:file:./target/h2db/db/flexApiDb;DB_CLOSE_DELAY=-1
        username: gm
        password:
    jpa:
      open-in-view: false
      hibernate:
        ddl-auto: none
        naming:
          physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
          implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
      show-sql: false
      properties:
        hibernate.id.new_generator_mappings: true
        hibernate.cache.use_second_level_cache: false
        hibernate.cache.use_query_cache: false
        hibernate.generate_statistics: false
    jackson:
      default-property-inclusion: non_null
      serialization:
        indent-output: true
        write-dates-as-timestamps: false
        write-date-timestamps-as-nanoseconds: false
        write-empty-json-arrays: false
      deserialization:
        fail-on-unknown-properties: false
        read-unknown-enum-values-using-default-value: true

liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml
